### ISSUE TITLE
Deprecation of io/ioutil

### ISSUE THREAD

**Issue by kiyadotdev** [supabase/postgrest-go#5]
# Chore

## Describe the chore

Hello 👋🏾 — I just started using `supabase` and was looking for a go client for `postgrest`. Nice work on this! 

I have a small refactor chore as it looks like the `postgrest-go` client uses go version `1.16` according to the `go.mod`. That being said, `io/ioutil` has been deprecated. Although the package remains and continues to work as we know, the go team encourages the use of new definitions found in `io` and `os` packages.

I have a small PR with the encouraged usage and will link to this issue for reference 😄 

## Additional context

More details can be read here: https://golang.org/doc/go1.16#ioutil

**Comment by kiyadotdev** [comment]
Here is the PR for reference: https://github.com/supabase/postgrest-go/pull/6 🤞🏾

**Comment by yusufpapurcu** [comment]
Merged #6
